# Copyright 2022 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Utilities to generate neighbor samples for link prediction models."""

import abc
import dataclasses
from typing import Optional, Union
import dataclasses_json
from dgf.src.data import in_memory_graph as in_memory_graph_lib
from dgf.src.data import schema as schema_lib
from dgf.src.sampling import in_memory_sampler as in_memory_sampler_lib
from dgf.src.util import dataclass_registry
import numpy as np

# TODO(gbm): Implement a PPR negative sampler, with an option to cache the PPR
# computation.

class AbstractNegativeNeighborSampler(abc.ABC):
  """Abstract class for negative samplers for link-predictions."""

  @abc.abstractmethod
  def sample(self, seed_edge_idxs: np.ndarray) -> np.ndarray:
    """Samples negative target nodes for a batch of seed positive edges.

    Args:
      seed_edge_idxs: A 1D array of edge indices to sample negatives for.

    Returns:
      A 2D array of shape (len(seed_edge_idxs), num_negative_neighbors)
      containing the indices of sampled negative target nodes.
    """


class RandomNegativeSampler(AbstractNegativeNeighborSampler):
  """Replace the target node with a random node.

  For each positive edge, a set of negative target nodes is generated by
  randomly sampling nodes from the target node set of the specified
  `target_edgeset`.

  Usage example:
  ```python
    sampler = RandomNegativeSampler(graph, schema, "e2", 3)
    neg_trg_nodes = sampler.sample(seed_edge_idxs)
  ```

  Attributes:
    graph: The in-memory graph containing the node and edge sets.
    schema: The graph schema defining the structure.
    target_edgeset: The name of the edge set for which negative targets are
      being sampled. The sampler will draw from the node set that is the target
      of this edge set.
    num_negative_neighbors: The number of negative target nodes to sample for
      each seed edge.
  """

  def __init__(
      self,
      graph: in_memory_graph_lib.InMemoryGraph,
      schema: schema_lib.GraphSchema,
      target_edgeset: str,
      num_negative_neighbors: int,
  ):
    self._schema = schema
    self._num_negative_neighbors = num_negative_neighbors
    self._num_nodes_in_target_nodeset = graph.node_sets[
        schema.edge_sets[target_edgeset].target
    ].num_nodes

  def sample(self, seed_edge_idxs: np.ndarray) -> np.ndarray:
    neg_trg_nodes = np.random.randint(
        0,
        self._num_nodes_in_target_nodeset,
        size=(len(seed_edge_idxs), self._num_negative_neighbors),
    )
    return neg_trg_nodes


class RandomWalkNegativeSampler(AbstractNegativeNeighborSampler):
  """Replace the target node with a random walk generated node.

  This class uses an existing sampler  for the random walk. The plan of this
  sampler defines the shape of the random walk.
  """

  def __init__(
      self,
      graph: in_memory_graph_lib.InMemoryGraph,
      schema: schema_lib.GraphSchema,
      target_edgeset: str,
      num_negative_neighbors: int,
      sampler: in_memory_sampler_lib.Sampler,
      num_walks: int,
  ):
    self._graph = graph
    self._target_edgeset = target_edgeset
    self._schema = schema
    self._num_negative_neighbors = num_negative_neighbors
    self._num_nodes_in_target_nodeset = graph.node_sets[
        schema.edge_sets[target_edgeset].target
    ].num_nodes
    self._sampler = sampler
    self._num_walks = num_walks
    self._target_edgeset_idx = (
        self._sampler._cc_sampler.EdgesetNameToEdgesetIdx(target_edgeset)
    )

  def _sample_from_seed_node_idxs(
      self, seed_node_idxs: np.ndarray
  ) -> np.ndarray:
    return self._sampler._cc_sampler.RandomWalkNegativeSampling(
        seed_node_idxs=seed_node_idxs,
        target_edgeset_idx=self._target_edgeset_idx,
        num_walks=self._num_walks,
        num_negatives_per_seed=self._num_negative_neighbors,
    )

  def sample(self, seed_edge_idxs: np.ndarray) -> np.ndarray:
    target_edgeset_data = self._graph.edge_sets[self._target_edgeset]
    seed_node_idxs = target_edgeset_data.adjacency[0][seed_edge_idxs]
    return self._sample_from_seed_node_idxs(seed_node_idxs)


@dataclasses.dataclass
class EdgeNeighborIdxs:
  """Indices of positive and negative neighbor nodes for a batch of edges.

  Attributes:
    pos_src_node_idxs: A 1D array of positive source node indices.
    pos_trg_node_idxs: A 1D array of positive target node indices.
    neg_trg_node_idxs: A 2D array of negative target node indices.
  """

  pos_src_node_idxs: np.ndarray
  pos_trg_node_idxs: np.ndarray
  neg_trg_node_idxs: np.ndarray


registry = dataclass_registry.create_registry("edge_neighbor_generator")


@registry.register
@dataclasses_json.dataclass_json
@dataclasses.dataclass
class RandomEdgeNeighborGeneratorConfig:
  pass


@registry.register
@dataclasses_json.dataclass_json
@dataclasses.dataclass
class RandomWalkEdgeNeighborGeneratorConfig:
  num_walks_per_negative: int = 10


EdgeNeighborGeneratorConfig = Union[
    RandomEdgeNeighborGeneratorConfig,
    RandomWalkEdgeNeighborGeneratorConfig,
]


class EdgeNeighborGenerator:
  """Generates the idx of the positive and negative pairs of nodes.

  Usage example:
  ```python
    generator = EdgeNeighborGenerator(graph, schema, "e2", 3)
    edge_neighbor_idxs = generator.generate(seed_edge_idxs)
  ```

  Attributes:
    graph: The in-memory graph.
    schema: The graph schema.
    target_edgeset: The name of the edge set to sample from.
    num_negative_neighbors: Number of negative neighbors to sample for each
      edge.
  """

  def __init__(
      self,
      graph: in_memory_graph_lib.InMemoryGraph,
      schema: schema_lib.GraphSchema,
      target_edgeset: str,
      num_negative_neighbors: int,
      *,
      sampler: Optional[in_memory_sampler_lib.Sampler] = None,
      config: EdgeNeighborGeneratorConfig = RandomEdgeNeighborGeneratorConfig(),
  ):
    if isinstance(config, RandomEdgeNeighborGeneratorConfig):
      self._negative_node_sampler = RandomNegativeSampler(
          graph, schema, target_edgeset, num_negative_neighbors
      )
    elif isinstance(config, RandomWalkEdgeNeighborGeneratorConfig):
      if sampler is None:
        raise ValueError(
            "A sampler must be provided when using the 'random-walk' method."
        )
      self._negative_node_sampler = RandomWalkNegativeSampler(
          graph,
          schema,
          target_edgeset,
          num_negative_neighbors,
          sampler,
          config.num_walks_per_negative * num_negative_neighbors,
      )
    else:
      raise ValueError(f"Unknown negative sampling config: {type(config)}")
    self._target_edgeset_data = graph.edge_sets[target_edgeset]

  def generate(self, seed_edge_idxs: np.ndarray) -> EdgeNeighborIdxs:
    """Generates positive and negative neighbor node indices for a batch of seed edges.

    Args:
      seed_edge_idxs: A 1D array of edge indices to generate neighbors for.

    Returns:
      An `EdgeNeighborIdxs` object containing the positive source, positive
      target, and negative target node indices.
    """

    pos_src_node_idxs = self._target_edgeset_data.adjacency[0][seed_edge_idxs]
    pos_trg_node_idxs = self._target_edgeset_data.adjacency[1][seed_edge_idxs]
    neg_trg_node_idxs = self._negative_node_sampler.sample(seed_edge_idxs)

    return EdgeNeighborIdxs(
        pos_src_node_idxs=pos_src_node_idxs,
        pos_trg_node_idxs=pos_trg_node_idxs,
        neg_trg_node_idxs=neg_trg_node_idxs,
    )
